{{- if .Values.auditService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apex-os-iam-pam.fullname" . }}-audit-service
  labels:
    {{- include "apex-os-iam-pam.labels" . | nindent 4 }}
    app.kubernetes.io/component: audit-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.auditService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "apex-os-iam-pam.name" . }}-audit-service
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
