{{- if .Values.authService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apex-os-iam-pam.fullname" . }}-auth-service
  labels:
    {{- include "apex-os-iam-pam.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.authService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "apex-os-iam-pam.name" . }}-auth-service
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
