{{- if .Values.monitoring.prometheus.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apex-os-iam-pam.fullname" . }}-prometheus-storage
  labels:
    {{- include "apex-os-iam-pam.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.global.storageClass }}
  resources:
    requests:
      storage: {{ .Values.monitoring.prometheus.storage }}
{{- end }}
