apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apex-os-iam-pam.fullname" . }}-secrets
  labels:
    {{- include "apex-os-iam-pam.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
type: Opaque
data:
  JWT_SECRET: {{ randAlphaNum 64 | b64enc | quote }}
  ENCRYPTION_KEY: {{ randAlphaNum 32 | b64enc | quote }}
  VAULT_TOKEN: {{ randAlphaNum 32 | b64enc | quote }}
  LDAP_BIND_PASSWORD: {{ randAlphaNum 32 | b64enc | quote }}
  OAUTH2_CLIENT_SECRET: {{ randAlphaNum 32 | b64enc | quote }}
  SAML_SIGNING_KEY: {{ randAlphaNum 64 | b64enc | quote }}
  TOTP_SECRET: {{ randAlphaNum 32 | b64enc | quote }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s-postgresql:5432/%s" .Values.postgresql.auth.username (randAlphaNum 16) (include "apex-os-iam-pam.fullname" .) .Values.postgresql.auth.database | b64enc | quote }}
  REDIS_URL: {{ printf "redis://%s-redis-master:6379" (include "apex-os-iam-pam.fullname" .) | b64enc | quote }}
